language: generic
services: docker

before_script:
- sudo apt-get -y install pdf2svg

script:
  # We use the docker image from https://hub.docker.com/r/dxjoke/tectonic-docker/
  # Compiling only main.tex:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic IPCookbook.tex"
  - pdf2svg IPCookbook.pdf IPCookbook%d.svg all
  - mkdir pdf
  - mv *{.svg,.pdf} pdf/.

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: pdf
  committer_from_gh: true
  on:
    branch: master
    
