language: generic
services: docker

before_script:
- git config --global user.email "ferreol.soulez@univ-lyon1.fr"
- git config --global user.name "ferreolS"

script:
  # We use the docker image from https://hub.docker.com/r/dxjoke/tectonic-docker/
  # Compiling only main.tex:
  - docker run --mount src=$TRAVIS_BUILD_DIR,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic IPCookbook.tex"
  
after_success:
  - git clone https://github.com/ferreolS/InverseProblemsCookbook pdf
  - cd pdf
  - git symbolic-ref HEAD refs/heads/gh-pages  # auto-switches branches to gh-pages
  - rm .git/index
  - git clean -fdx
  - mv ../IPCookbook.pdf .
  - git add *
  - git commit -a -m "Add Doc"
  - git push --force  https://${GH_TOKEN}@github.com/ferreolS/InverseProblemsCookbook gh-pages
  